locals {
  ssh_key_expanded = pathexpand(var.ssh_private_key_path)

  # External (already-existing) etcd members have no Terraform-managed facts;
  # they appear in the inventory with their name echoed as ansible_host and no
  # data_disk_* / private_ip / zone / instance_type vars. Operators can override
  # via host_vars / group_vars.
  database_inventory = [
    for n in var.database_hosts : {
      name              = n
      ip                = try(var.vm_facts[n].public_ip, n)
      data_disk_size_gb = try(var.vm_facts[n].data_disk_size_gb, 0)
      data_disk_device  = try(var.vm_facts[n].data_disk_device, "")
    }
  ]

  etcd_inventory = [
    for n in var.resolved_etcd_hosts : {
      name              = n
      ip                = try(var.vm_facts[n].public_ip, n)
      data_disk_size_gb = try(var.vm_facts[n].data_disk_size_gb, 0)
      data_disk_device  = try(var.vm_facts[n].data_disk_device, "")
    }
  ]

  # HAProxy + dedicated pgBackRest backup-server tiers. Both are optional (empty
  # lists when unused) and, unlike etcd, are always Terraform-provisioned vms, so
  # vm_facts are always present. Same shape as database_inventory.
  haproxy_inventory = [
    for n in var.haproxy_hosts : {
      name              = n
      ip                = try(var.vm_facts[n].public_ip, n)
      data_disk_size_gb = try(var.vm_facts[n].data_disk_size_gb, 0)
      data_disk_device  = try(var.vm_facts[n].data_disk_device, "")
    }
  ]

  backup_inventory = [
    for n in var.backup_hosts : {
      name              = n
      ip                = try(var.vm_facts[n].public_ip, n)
      data_disk_size_gb = try(var.vm_facts[n].data_disk_size_gb, 0)
      data_disk_device  = try(var.vm_facts[n].data_disk_device, "")
    }
  ]

  # YAML inventory: hostvars live at all.hosts.<name>; groups just reference
  # names. Avoids the var-merge gymnastics that come with listing hostvars
  # under each group's hosts: mapping.
  all_hosts = distinct(concat(
    var.database_hosts,
    var.resolved_etcd_hosts,
    var.haproxy_hosts,
    var.backup_hosts,
  ))

  hostvars_yaml = {
    for n in local.all_hosts : n => merge(
      {
        ansible_host                 = try(var.vm_facts[n].public_ip, n)
        ansible_user                 = var.ssh_user
        ansible_ssh_private_key_file = local.ssh_key_expanded
      },
      contains(keys(var.vm_facts), n) ? {
        private_ip        = var.vm_facts[n].private_ip
        zone              = var.vm_facts[n].zone
        instance_type     = var.vm_facts[n].instance_type
        data_disk_size_gb = var.vm_facts[n].data_disk_size_gb
        data_disk_device  = var.vm_facts[n].data_disk_device
      } : {}
    )
  }

  inventory_yaml = {
    all = {
      vars = {
        ansible_python_interpreter = "/usr/bin/python3"
      }
      hosts = local.hostvars_yaml
      children = {
        database_hosts = {
          hosts = { for n in var.database_hosts : n => {} }
        }
        etcd_cluster = {
          hosts = { for n in var.resolved_etcd_hosts : n => {} }
        }
        haproxy = {
          hosts = { for n in var.haproxy_hosts : n => {} }
        }
        backup_server = {
          hosts = { for n in var.backup_hosts : n => {} }
        }
      }
    }
  }

  credentials = {
    provider             = var.provider_name
    ssh_user             = var.ssh_user
    ssh_private_key_file = local.ssh_key_expanded
    ssh_public_key_file  = pathexpand(var.ssh_public_key_path)
    generated_at         = timestamp()
  }
}

resource "local_file" "inventory" {
  filename        = var.inventory_output_path
  file_permission = "0644"

  content = templatefile("${path.module}/templates/ansible_inventory.tmpl", {
    provider             = var.provider_name
    generated_at         = timestamp()
    ssh_user             = var.ssh_user
    ssh_private_key_file = local.ssh_key_expanded
    database_hosts       = local.database_inventory
    etcd_hosts           = local.etcd_inventory
    haproxy_hosts        = local.haproxy_inventory
    backup_hosts         = local.backup_inventory
  })
}

resource "local_file" "inventory_yaml" {
  filename        = var.inventory_yaml_output_path
  file_permission = "0644"
  content = join("\n", [
    "# Generated by Terraform — do not edit manually",
    "# Provider: ${var.provider_name} | Applied: ${timestamp()}",
    yamlencode(local.inventory_yaml),
  ])
}

resource "local_sensitive_file" "credentials" {
  filename        = var.credentials_output_path
  file_permission = "0600"
  content         = jsonencode(local.credentials)
}
